active_list: '719'
lists:
  '509':
    Aishu: 0
    Arron: 0
    Jeri: 0
    Jin: 0
    Miri: 0
    Sven: 0
    Yohei: 0
  '719':
    Riadh: 0
    Doug: 0
    Kyle: 0
    Abe: 0
    Yifei: 0
    Stephy: 0